name: Execute Workflows

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  execute-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Workflows
        run: |
          curl -X POST ${{ secrets.SITE_URL }}/api/execute-workflows \
            -H "Content-Type: application/json" \
            --fail-with-body
        env:
          SITE_URL: ${{ secrets.SITE_URL }} 